### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Reyesjessica** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Reyesjessica#1]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Reyesjessica/files/14528044/Infografia.pdf)

**Comment by AricelCastro** [comment]
Nuestro equipo le da una calificación de 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
